Fixed error CS0619 for Unity 6.5+
error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

This forced me to uprise minimal version of Unity required to run package to 6000.5